
install:
  # Local
  - sudo apt-get install -qq luatex texlive-base texlive-luatex luarocks
  # Global 
  - sudo apt-get install -qq pandoc latexmk texlive texlive-xetex  texlive-fonts-extra

script:
  # Already runs locally
  - ./make4ht -v
  - luarocks --local install busted
  - git fetch --tags
  - make
  - sudo make install
  # - make test
  # Now runs globally
  - make4ht -v
